const questions = [
    {id: 1, text: "Saya senang bertemu orang baru di acara sosial", dim: "EI", dir: 1},
    {id: 2, text: "Saya lebih suka menghabiskan malam sendiri daripada pergi ke pesta", dim: "EI", dir: -1},
    {id: 3, text: "Saya mudah berbicara dengan orang yang baru saya kenal", dim: "EI", dir: 1},
    {id: 4, text: "Saya merasa lelah setelah menghabiskan waktu lama bersama banyak orang", dim: "EI", dir: -1},
    {id: 5, text: "Saya suka menjadi pusat perhatian", dim: "EI", dir: 1},
    {id: 6, text: "Saya lebih suka bekerja sendiri daripada dalam kelompok", dim: "EI", dir: -1},
    {id: 7, text: "Saya senang memulai percakapan dengan orang asing", dim: "EI", dir: 1},
    {id: 8, text: "Saya butuh waktu sendiri untuk mengisi ulang energi", dim: "EI", dir: -1},
    {id: 9, text: "Saya memiliki banyak teman dan kenalan", dim: "EI", dir: 1},
    {id: 10, text: "Saya lebih suka mendengarkan daripada berbicara dalam diskusi", dim: "EI", dir: -1},
    {id: 11, text: "Saya senang bekerja dalam tim", dim: "EI", dir: 1},
    {id: 12, text: "Saya lebih nyaman dengan sedikit teman dekat daripada banyak teman", dim: "EI", dir: -1},
    {id: 13, text: "Saya suka berbagi pikiran saya dengan orang lain", dim: "EI", dir: 1},
    {id: 14, text: "Saya lebih suka berpikir dulu sebelum berbicara", dim: "EI", dir: -1},
    {id: 15, text: "Saya merasa bersemangat di keramaian", dim: "EI", dir: 1},
    {id: 16, text: "Saya lebih suka fakta daripada teori", dim: "SN", dir: 1},
    {id: 17, text: "Saya sering memikirkan kemungkinan-kemungkinan di masa depan", dim: "SN", dir: -1},
    {id: 18, text: "Saya fokus pada detail kecil", dim: "SN", dir: 1},
    {id: 19, text: "Saya lebih suka melihat gambaran besar daripada detail", dim: "SN", dir: -1},
    {id: 20, text: "Saya percaya pada pengalaman nyata", dim: "SN", dir: 1},
    {id: 21, text: "Saya suka membayangkan hal-hal yang belum terjadi", dim: "SN", dir: -1},
    {id: 22, text: "Saya lebih suka instruksi yang jelas dan spesifik", dim: "SN", dir: 1},
    {id: 23, text: "Saya suka mencari makna tersembunyi dari sesuatu", dim: "SN", dir: -1},
    {id: 24, text: "Saya lebih praktis daripada imajinatif", dim: "SN", dir: 1},
    {id: 25, text: "Saya sering berpikir tentang konsep abstrak", dim: "SN", dir: -1},
    {id: 26, text: "Saya lebih suka hal-hal yang konkret", dim: "SN", dir: 1},
    {id: 27, text: "Saya suka berimajinasi dan berkreasi", dim: "SN", dir: -1},
    {id: 28, text: "Saya memperhatikan hal-hal yang orang lain lewatkan", dim: "SN", dir: 1},
    {id: 29, text: "Saya lebih tertarik pada ide daripada fakta", dim: "SN", dir: -1},
    {id: 30, text: "Saya suka bekerja dengan hal-hal yang nyata", dim: "SN", dir: 1},
    {id: 31, text: "Saya membuat keputusan berdasarkan logika", dim: "TF", dir: 1},
    {id: 32, text: "Saya mempertimbangkan perasaan orang lain saat membuat keputusan", dim: "TF", dir: -1},
    {id: 33, text: "Saya lebih mementingkan kebenaran daripada perasaan", dim: "TF", dir: 1},
    {id: 34, text: "Saya mudah merasakan emosi orang lain", dim: "TF", dir: -1},
    {id: 35, text: "Saya suka menganalisis masalah secara objektif", dim: "TF", dir: 1},
    {id: 36, text: "Saya sering membuat keputusan berdasarkan perasaan", dim: "TF", dir: -1},
    {id: 37, text: "Saya lebih suka kritik yang jujur meskipun menyakitkan", dim: "TF", dir: 1},
    {id: 38, text: "Saya menghindari konflik untuk menjaga harmoni", dim: "TF", dir: -1},
    {id: 39, text: "Saya membuat keputusan berdasarkan data dan fakta", dim: "TF", dir: 1},
    {id: 40, text: "Saya mempertimbangkan dampak keputusan pada orang lain", dim: "TF", dir: -1},
    {id: 41, text: "Saya lebih rasional daripada emosional", dim: "TF", dir: 1},
    {id: 42, text: "Saya mudah berempati dengan masalah orang lain", dim: "TF", dir: -1},
    {id: 43, text: "Saya suka debat intelektual", dim: "TF", dir: 1},
    {id: 44, text: "Saya lebih mementingkan hubungan baik daripada benar", dim: "TF", dir: -1},
    {id: 45, text: "Saya percaya keadilan lebih penting daripada belas kasihan", dim: "TF", dir: 1},
    {id: 46, text: "Saya suka membuat rencana dan menepatinya", dim: "JP", dir: 1},
    {id: 47, text: "Saya lebih suka spontan dan fleksibel", dim: "JP", dir: -1},
    {id: 48, text: "Saya menyelesaikan tugas lebih awal", dim: "JP", dir: 1},
    {id: 49, text: "Saya sering menunda pekerjaan sampai mendekati deadline", dim: "JP", dir: -1},
    {id: 50, text: "Saya suka segala sesuatu teratur dan terencana", dim: "JP", dir: 1},
    {id: 51, text: "Saya nyaman dengan perubahan mendadak", dim: "JP", dir: -1},
    {id: 52, text: "Saya membuat daftar tugas dan mengikutinya", dim: "JP", dir: 1},
    {id: 53, text: "Saya suka menjaga opsi saya tetap terbuka", dim: "JP", dir: -1},
    {id: 54, text: "Saya merasa stres jika segala sesuatu tidak terencana", dim: "JP", dir: 1},
    {id: 55, text: "Saya lebih suka mengalir saja", dim: "JP", dir: -1},
    {id: 56, text: "Saya suka menyelesaikan satu hal sebelum memulai yang lain", dim: "JP", dir: 1},
    {id: 57, text: "Saya sering mengerjakan beberapa hal sekaligus", dim: "JP", dir: -1},
    {id: 58, text: "Saya memiliki rutinitas harian yang tetap", dim: "JP", dir: 1},
    {id: 59, text: "Saya suka petualangan dan hal-hal tak terduga", dim: "JP", dir: -1},
    {id: 60, text: "Saya merasa puas saat mencentang tugas yang selesai", dim: "JP", dir: 1}
];
